[project]
name = "py-chroma-mcp"
version = "0.1.0"
description = "A simple Model Context Protocol (MCP) server using stdio."
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.10"
dependencies = [
    "chromadb>=0.4.0",
    "mcp>=1.0.0",
    "langchain>=0.1.0",
    "langchain-community", 
    "langchain-chroma",
    "transformers>=4.30.0",
    "sentence-transformers>=2.2.0",
    "torch>=2.0.0",
    "huggingface-hub>=0.16.0",
    "pydantic>=2.0.0",
    "typing-extensions>=4.5.0"
]

[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312"]

[tool.isort]
profile = "black"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
