[project]
name = "py-chroma-mcp"
version = "0.1.0"
description = "A simple Model Context Protocol (MCP) server using stdio."
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.10"
dependencies = [
    "chromadb",
    "mcp",
    "langchain>=0.1.0",
    "langchain-community", 
    "langchain-chroma",
    "transformers",
    "sentence-transformers",
    "torch"
]

[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312"]

[tool.isort]
profile = "black"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
