services:
  py_chroma_mcp:
    container_name: py_chroma_mcp
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: development
    # env_file:
    #   - .env
    environment:
      - PYTHONPATH=/workspace
      - ENVIRONMENT=development
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace:cached
    ports:
      - "3000:3000"
    restart: unless-stopped
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
