# Generated by Copilot
"""
Utils module for ChromaDB MCP server utilities.

Provides common utilities for metrics, validation, and helper functions.
"""

from .metrics import (
    MetricsCollector,
    get_metrics_collector,
    benchmark_function,
    measure_memory_usage,
    track_execution_time,
)

from .validators import (
    ValidationResult,
    InputValidator,
    CollectionValidator,
    DocumentValidator,
    QueryValidator,
    ValidationOrchestrator,
    validator,
)

from .error_handler import (
    ErrorContext,
    ErrorTracker,
    get_error_tracker,
    handle_mcp_tool_errors,
    log_operation_start,
    log_operation_success,
    log_operation_error,
    OperationContext,
)

__all__ = [
    # Metrics
    "MetricsCollector",
    "get_metrics_collector",
    "benchmark_function",
    "measure_memory_usage",
    "track_execution_time",
    # Validators
    "ValidationResult",
    "InputValidator",
    "CollectionValidator",
    "DocumentValidator",
    "QueryValidator",
    "ValidationOrchestrator",
    "validator",
    # Error handling
    "ErrorContext",
    "ErrorTracker",
    "get_error_tracker",
    "handle_mcp_tool_errors",
    "log_operation_start",
    "log_operation_success",
    "log_operation_error",
    "OperationContext",
]

# Version info
__version__ = "1.0.0"
