# Generated by Copilot
"""
Embedding module for ChromaDB MCP server.

This module provides comprehensive embedding functionality including:
- Embedding model management and loading
- Intelligent text chunking for better embeddings
- Hugging Face authentication and token management
- Vector quality assessment and optimization

Features:
- Support for multiple embedding models (sentence-transformers, etc.)
- Vietnamese-optimized text chunking
- Caching and performance optimization
- Error handling and graceful fallbacks
"""

from .manager import (
    EmbeddingManager,
)

from .chunker import (
    TextChunker,
    ChunkingStrategy,
    chunk_text_intelligent,
    chunk_text_semantic,
    optimize_chunk_size,
)

__all__ = [
    # Model management
    "EmbeddingManager",
    # Text chunking
    "TextChunker",
    "ChunkingStrategy",
    "chunk_text_intelligent",
    "chunk_text_semantic",
    "optimize_chunk_size",
]

# Version info
__version__ = "1.0.0"
