# Generated by Copilot
"""
Embedding module for ChromaDB MCP server.

This module provides comprehensive embedding functionality including:
- Embedding model management and loading
- Intelligent text chunking for better embeddings
- Hugging Face authentication and token management
- Vector quality assessment and optimization

Features:
- Support for multiple embedding models (sentence-transformers, etc.)
- Vietnamese-optimized text chunking
- Caching and performance optimization
- Error handling and graceful fallbacks
"""

from .manager import (
    EmbeddingManager,
)

# Batch processor imports removed to avoid circular dependency
# Can be imported directly as: from embedding.batch_processor import BatchProcessor

from .chunker import (
    TextChunker,
    ChunkingStrategy,
    chunk_text_intelligent,
    chunk_text_semantic,
    optimize_chunk_size,
)

__all__ = [
    # Manager
    "EmbeddingManager",
    # Batch Processing - import directly from embedding.batch_processor
    # "BatchProcessor",
    # "EmbeddingCache",
    # Chunking
    "TextChunker",
    "ChunkingStrategy",
    "chunk_text_intelligent",
    "chunk_text_semantic",
    "optimize_chunk_size",
]

# Version info
__version__ = "1.0.0"
