"""
py-chroma-mcp: A simple Model Context Protocol server with ChromaDB integration.
Generated by Copilot
"""

__version__ = "0.1.0"
__author__ = "Mai Thành Duy An vs Copilot"
__email__ = "tiachop0102@gmail.com"
