# Generated by Copilot
"""
ChromaDB MCP Server Package

A Model Context Protocol (MCP) server that provides tools for interacting with ChromaDB,
including document storage, retrieval, and semantic search capabilities.
"""

__version__ = "0.1.0"
__author__ = "Copilot"

from .server import main

__all__ = ["main"]
